project:
  type: book
  output-dir: docs
  
book:
  title: Computer-Aided Statistical Analysis (B.Sc.)
  author: Prof. Dr. Dominik Liebl 
  search: true
  logo: images/Uni_Bonn_Logo.jpeg
  number-sections: TRUE
  crossref:
    chapters: true
  chapters:
    - index.qmd
    - Ch2_RLab.qmd # Reads in Ch2_Solutions.qmd
    - Ch3_RLab.qmd # Reads in Ch3_Solutions.qmd
    - Ch4_RLab.qmd # Reads in Ch4_Solutions.qmd
    - Ch5_RLab.qmd # Reads in Ch5_Solutions.qmd
    - Ch6_RLab.qmd # Reads in Ch6_Solutions.qmd

#bibliography: references.bib

format:
  html:
    theme: cosmo
