project:
  type: book
  output-dir: docs
  
book:
  title: Computer-Aided Statistical Analysis B.Sc.
  author: Prof. Dr. Dominik Liebl 
  search: true
  logo: images/Uni_Bonn_Logo.jpeg
  number-sections: TRUE
  crossref:
    chapters: true
  chapters:
    - index.qmd
    - Ch2_RLab.qmd
    # - Ch2_Exercises.qmd
    #- 04-MultipleReg.qmd
    #- 05-Small-Sample-Inference.qmd
    #- 06-Asymptotics.qmd
    #- 08-Instrumental-Variables.qmd
    # - references.qmd

#bibliography: references.bib

format:
  html:
    theme: cosmo
