project:
  type: book
  output-dir: docs
  
book:
  title: Computer-Aided Statistical Analysis (B.Sc.)
  author: Prof. Dr. Dominik Liebl 
  date: last-modified
  date-format: "[Last Updated on] MMMM DD, YYYY"
  sidebar: 
    logo: images/Uni_Bonn_Logo.jpeg
    number-depth: 2
  search: true
  chapters:
    - index.qmd
    - Ch1_Intro2R.qmd
    - Ch2_StatLearning.qmd      # Reads in Ch2_StatLearning_Solutions.qmd
    - Ch3_MatrixAlgebra.qmd
    - Ch4_LinearRegression.qmd  # Reads in Ch2_Solutions.qmd
    - Ch5_Classification.qmd    # Reads in Ch3_Solutions.qmd
    - Ch6_ResamplingMethods.qmd # Reads in Ch4_Solutions.qmd
    #- Ch7_LinModSelectRegul.qmd # Reads in Ch5_Solutions.qmd

#bibliography: references.bib

format:
  html:
    theme:
      light: [flatly, theme.scss]
      dark: [flatly, darkly, theme.scss]
    html-math-method:
      method: mathjax
      url: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML"
    number-sections: true
    code-link: true
    reference-links: true
    reference-location: margin
    knitr:
      opts_chunk:
        fig.align: center
        fig-align: center
